In [1]:
import numpy as np
a = np.array([1, 2, 3, 4])      # 리스트 → 배열
print(a, type(a))
print(np.zeros(3))              # 0으로 채운 배열
print(np.ones(3))              # 1로 채운 배열
print(np.arange(0, 10, 2))     # 0~10 미만, 2씩

[1 2 3 4] <class 'numpy.ndarray'>
[0. 0. 0.]
[1. 1. 1.]
[0 2 4 6 8]


In [2]:
a = np.array([1, 2, 3, 4])
print('shape:', a.shape)   # (4,)
print('ndim :', a.ndim)    # 1차원
print('dtype:', a.dtype)   # 데이터 타입

shape: (4,)
ndim : 1
dtype: int64


In [3]:
a = np.array([10, 20, 30, 40, 50])
print(a[0])      # 10
print(a[-1])     # 50
print(a[1:4])    # [20 30 40]

10
50
[20 30 40]


In [4]:
m = np.array([[1, 2, 3],
              [4, 5, 6]])
print('shape:', m.shape)   # (2, 3) = 2행 3열
print('첫 행 :', m[0])      # [1 2 3]
print('[0,2]:', m[0, 2])   # 3 (0행 2열)
print('1번 열:', m[:, 1])   # [2 5]  ← 모든 행의 1번 열
# ML 예: pred[:, 1] → 예측확률에서 '1(양성)일 확률' 열만 뽑기


shape: (2, 3)
첫 행 : [1 2 3]
[0,2]: 3
1번 열: [2 5]


In [5]:
a = np.array([1, 2, 3, 4])
print(a * 2)        # [2 4 6 8]   각 원소에 곱
print(a + 10)       # [11 12 13 14]
print(a + a)        # [2 4 6 8]   같은 위치끼리
print(a.mean())     # 평균


[2 4 6 8]
[11 12 13 14]
[2 4 6 8]
2.5


In [6]:
a = np.array([10, 25, 30, 5, 40])
print(a > 20)          # [False  True  True False  True]
print(a[a > 20])       # [25 30 40]  ← 조건 True인 값만


[False  True  True False  True]
[25 30 40]


In [7]:
m = np.array([[1, 2, 3],
              [4, 5, 6]])
print('전체 합 :', m.sum())
print('열별 합 :', m.sum(axis=0))   # [5 7 9]  세로로
print('행별 합 :', m.sum(axis=1))   # [6 15]   가로로
print('평균/최대/표준편차:', m.mean(), m.max(), round(m.std(), 2))


전체 합 : 21
열별 합 : [5 7 9]
행별 합 : [ 6 15]
평균/최대/표준편차: 3.5 6 1.71


In [9]:
a = np.arange(6)           # [0 1 2 3 4 5]
print("--")
print(a.reshape(2, 3))     # 2행 3열
print("--")
print(a.reshape(3, 2))     # 3행 2열
print("--")
print(a.reshape(-1, 1))    # -1 = 자동 계산 (여기선 6행 1열)


--
[[0 1 2]
 [3 4 5]]
--
[[0 1]
 [2 3]
 [4 5]]
--
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
# 9-1. np.where / astype -- 확률 → 0/1 라벨 (임계값 분류)
proba = np.array([0.2, 0.8, 0.55, 0.4])
print(np.where(proba >= 0.5, 1, 0))       # 0.5 이상이면 1, 아니면 0
print((proba >= 0.5).astype(int))         # 불리언 → 0/1 (같은 결과)

# 9-2. argmax -- 가장 큰 값의 '위치' (다중분류 예측 클래스, 05)
scores = np.array([0.1, 0.7, 0.2])
print(scores.argmax())                    # 1 (가장 큰 0.7의 위치)

# 9-3. np.unique -- 클래스/고유값 + 개수
y = np.array([0, 1, 1, 2, 0, 2, 2])
print(np.unique(y))                       # [0 1 2]
print(np.unique(y, return_counts=True))   # 값과 개수

# 9-4. seed -- 재현성 (random_state의 원리)
np.random.seed(0); print(np.random.rand(3))
np.random.seed(0); print(np.random.rand(3))   # 시드 같으면 같은 결과


In [ ]:
# 1) 다양한 배열 만들기
print(np.zeros((2, 3)))       # 2x3 0 배열
print(np.full(3, 7))          # [7 7 7]
print(np.linspace(0, 1, 5))   # 0~1을 5등분 [0. 0.25 0.5 0.75 1.]

# 2) 전치 .T -- 행<->열 뒤집기
m = np.array([[1, 2, 3], [4, 5, 6]])
print(m.shape, '->', m.T.shape)   # (2, 3) -> (3, 2)
print(m.T)

# 3) 집계 -- 함수형/메서드형 둘 다 + 반올림
a = np.array([10, 25, 30, 5, 40])
print(np.mean(a), a.mean())       # 같은 결과
print(np.round(a.mean(), 2))      # 반올림(평가 출력에서 자주)

# 4) 조건 개수 세기 -- (조건).sum() (매우 유용)
print((a > 20).sum())             # 20 초과 개수 = 3

# 5) 합치기 concatenate
b = np.array([1, 2]); c = np.array([3, 4])
print(np.concatenate([b, c]))     # [1 2 3 4]
